# Generated by Django 3.1.7 on 2021-07-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
